/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EejgYXkrNnc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Clientcomponent() {
  return (
    (<div className="mx-auto max-w-md space-y-6 py-12 px-4 sm:px-6 lg:px-8">
      <div className="text-center">
        <h2
          className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Register for eCourts</h2>
        <p className="mt-3 text-base text-gray-500 dark:text-gray-400">
          Create your account to access the eCourts platform.
        </p>
      </div>
      <form className="space-y-6">
        <div className="grid grid-cols-2 gap-6">
          <div>
            <Label htmlFor="first-name">First Name</Label>
            <Input id="first-name" placeholder="Enter your first name" required type="text" />
          </div>
          <div>
            <Label htmlFor="last-name">Last Name</Label>
            <Input id="last-name" placeholder="Enter your last name" required type="text" />
          </div>
        </div>
        <div>
          <Label htmlFor="date-of-birth">Date of Birth</Label>
          <Input
            id="date-of-birth"
            placeholder="Enter your date of birth"
            required
            type="date" />
        </div>
        <div>
          <Label htmlFor="username">Username</Label>
          <Input id="username" placeholder="Enter your username" required type="text" />
        </div>
        <div>
          <Label htmlFor="password">Password</Label>
          <Input id="password" placeholder="Enter your password" required type="password" />
        </div>
        <Button className="w-full" type="submit">
          Sign Up
        </Button>
      </form>
    </div>)
  );
}
