/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FzhuYeyzX8E
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"

export function JudgePJ() {
  return (<>
    <header
      className="flex items-center justify-between h-16 px-4 border-b shrink-0 md:px-6">
      <div className="flex items-center gap-4">
        <span className="text-lg font-medium">Welcome Judge</span>
      </div>
      <div className="flex items-center gap-4">
        <Button variant="link">View Account</Button>
        <Button variant="outline">Logout</Button>
      </div>
    </header>
    <main className="flex flex-col gap-8 p-4 md:p-10">
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Search for details for active cases</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Input className="flex-1" placeholder="Enter CNR number" type="text" />
              <Button>Search</Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Search for previous judgments</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              <div className="flex items-center gap-2">
                <Select>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Search by CNR number" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectItem value="cnr">Search by CNR number</SelectItem>
                    </SelectGroup>
                  </SelectContent>
                </Select>
                <Button>Search</Button>
              </div>
              <div className="flex items-center gap-2">
                <Select>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Search by Acts" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectItem value="acts">Search by Acts</SelectItem>
                    </SelectGroup>
                  </SelectContent>
                </Select>
                <Button>Search</Button>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Enter details and search</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Input className="flex-1" placeholder="Enter details" type="text" />
              <Button>Search</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  </>);
}
