/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YnWUUfiMgUS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function JudgeCases2() {
  return (<>
    <header
      className="text-gray-900 dark:text-white py-4 px-6 flex justify-between items-center">
      <h1 className="text-2xl font-bold">Welcome Judge</h1>
      <div className="flex gap-4">
        <Button variant="outline">View Account</Button>
        <Button>Logout</Button>
      </div>
    </header>
    <main className="container mx-auto my-8 px-4 sm:px-6 lg:px-8">
      <div
        className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="text-gray-500 dark:text-gray-400">Search for Details</div>
        <div className="flex items-center gap-4 w-full sm:w-auto">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="flex-1 sm:flex-none" variant="outline">
                Lawyer ID
                <ChevronDownIcon className="ml-2 h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start">
              <DropdownMenuCheckboxItem>123456</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>789012</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>345678</DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="flex-1 sm:flex-none" variant="outline">
                Civilian ID
                <ChevronDownIcon className="ml-2 h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start">
              <DropdownMenuCheckboxItem>987654</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>321098</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>654321</DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <div className="flex-1 sm:flex-none">
            <Label htmlFor="id">Enter ID</Label>
            <Input id="id" placeholder="Enter ID" type="text" />
          </div>
          <Button>Search</Button>
        </div>
      </div>
    </main>
  </>);
}

function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}
